#!/bin/sh

make_wallpaper() {
	_wallpaperdir="$HOME"/Pictures/wallpaper/pics-current/
	xwallpaper --output eDP-1 --maximize "$(find "${_wallpaperdir}" -type f | sort -R | head -1)" --output DP-1 --maximize "$(find "${_wallpaperdir}" -type f | sort -R | head -1)"
}

make_xbmpaper() {
	BLACK="#000000"
	#BLUE="#3b48e3"
	#GREEN="#18b218"
	GREY="#656565"
	#RED="#b81313"
	#YELLOW="#b4801e"
	_xbmdir="$HOME"/Pictures/wallpaper/xbm-current/
	while true ; do
		xsetroot -bitmap "$(find "${_xbmdir}" -iname '*.xbm' | sort -R | head -1)" -bg $GREY -fg $BLACK
		sleep 3600
	done
}

if command -v xwallpaper > /dev/null ; then
	make_wallpaper
else
	make_xbmpaper
fi
