#!/bin/sh

_bardir="$HOME/sources/termbar"
_monitors=$(xprop -root _NET_DESKTOP_GEOMETRY | awk -F " = " '{ print $2 }')

autoselect() {
	if command -v lemonbar > /dev/null ; then
		make_lemonbar
	else
		make_termbar
	fi
}

clean_up_bars() {
	kill -9 "$(pgrep -f termbar)"
	pkill lemonbar
	pkill xbattbar
}

make_lemonbar() {
	_font="-misc-fixed-medium-r-normal-*-15-*-*-*-*-*-iso10646-1"
	_colour="#000000"
	_fontcolour="#d8d8d8"
	_left="1920x20+0+0"
	_right="1920x20+1920+0"
	if [ "${_monitors}" = "3840, 1080" ] ; then
		"${_bardir}"/lemonscript.sh | lemonbar -dp -g "${_left}" -B "${_colour}" -F "${_fontcolour}" -f "${_font}" &
		"${_bardir}"/lemonscript.sh | lemonbar -dp -g "${_right}" -B "${_colour}" -F "${_fontcolour}" -f "${_font}" &
	elif [ "${_monitors}" = "1920, 1080" ] ; then
		"${_bardir}"/lemonscript.sh | lemonbar -dp -g "${_left}" -B "${_colour}" -F "${_fontcolour}" -f "${_font}" &
	fi
}

make_termbar() {
	_left="214x1+0+0"
	_right="214x1+1920+0"
	if [ "${_monitors}" = "3840, 1080" ] ; then
		xterm -name termbar -class termbar -geometry "${_left}" -e "${_bardir}"/termbar.sh &
		xterm -name termbar -class termbar -geometry "${_right}" -e "${_bardir}"/termbar.sh &
	elif [ "${_monitors}" = "1920, 1080" ] ; then
		xterm -name termbar -class termbar -geometry "${_left}" -e "${_bardir}"/termbar.sh &
	fi
}

make_xbattbar() {
	xbattbar -a -p 30 -T top &
}

case $1 in
l)
	clean_up_bars
	make_lemonbar
	;;
t)
	clean_up_bars
	make_termbar
	;;
x)
	clean_up_bars
	make_xbattbar
	;;
*)
	clean_up_bars
	autoselect
esac
