#!/bin/sh

if [ -n "$2" ] ; then
	_url_info=$(youtube-dl -F "$2")
	if echo "${_url_info}" | grep -q '\[download\] Downloading video 2' ; then
		_rest_starts=$(echo "${_url_info}" | grep -n '\[download\] Downloading video 2' | cut -d ':' -f 1)
	else
		_rest_starts=$(echo "${_url_info}" | grep -c '')
	fi
	_stream_id=$(echo "${_url_info}" | head -"${_rest_starts}" | grep -v 'audio only' | awk -F " " '/^hls|^http|^mp4/ { print $1 }' | tail -1)
else
	usage
fi

download_stream() {
	youtube-dl -f "${_stream_id}" "$2"
}

watch_with_mpv() {
	mpv --ytdl-raw-options=format="${_stream_id}" "$2"
}

usage() { cat << USAGE
${0##*/} - Watch or download videos from sites with non-standard stream IDs.
usage: ${0##*/}	download -> Download the best quality stream.
		watch    -> Watch the best quality stream with mpv(1).
USAGE
	exit 1
}

case $1 in
	d*) download_stream "$@" ;;
	w*) watch_with_mpv "$@" ;;
	*) usage ;;
esac
