#!/bin/sh

trap 'exec $0' HUP # Restart itself
trap 'tput cnorm; exit 1' INT QUIT TERM

esc="\033"
reset="${esc}[0m"
redf="${esc}[31m"
cyanf="${esc}[36m";
purplef="${esc}[35m"
pipe="${purplef}|${reset}"

time() {
	DATE=$(date '+%A, %d %B %Y ● %T %Z %z ● %V ● %j')
}

group() {
	GROUP=$(xprop -root _NET_CURRENT_DESKTOP | cut -d ' ' -f 3)
}

cpu() {
	CPU_TEMP=$(sysctl hw.sensors.cpu0.temp0 | cut -d "=" -f 2 | cut -d "." -f 1)
	CPU_SPEED=$(printf "%4s" "$(sysctl hw.cpuspeed | cut -d "=" -f 2 | cut -d "." -f 1)")
}

bat() {
	BAT=$(apm -l)
}

bat_status() {
	STATUS=$(sysctl hw.sensors.acpiac0.indicator0 | grep -c On)
	if [ "${STATUS}" -eq "1" ]; then
		BAT_STATUS=Connected
	else
		BAT_STATUS=${redf}Disconnected${reset}
	fi
}

mem() {
	MEM=$(top -n | grep Memory | awk '{ print $6 }')
}

wifi() {
	SSID=$(ifconfig | grep join | sed -e 's/.*join\(.*\)chan.*/\1/')
}

tput civis

while true; do
	time
	group
	cpu
	mem
	bat
	bat_status
	wifi
	tput cup 1 0
	printf "[${GROUP}] ${DATE} ${pipe} ${cyanf}CPU:${reset} ${CPU_SPEED} MHz (${CPU_TEMP}°) ${pipe} ${cyanf}Mem:${reset} ${MEM} "
	printf "${pipe} ${cyanf}Bat:${reset} $BAT - ${BAT_STATUS} ${pipe} ${cyanf}SSID:${reset}${SSID}${pipe}"
	sleep 1
done
