#!/bin/sh
# This requires the following lines in
# /etc/doas.conf
# permit nopass alexander as root cmd sysctl args kern.audio.record=0
# permit nopass alexander as root cmd sysctl args kern.audio.record=1
# permit nopass alexander as root cmd sysctl args kern.video.record=0
# permit nopass alexander as root cmd sysctl args kern.video.record=1

doas sysctl kern.video.record=1
doas sysctl kern.audio.record=1

ENABLE_WASM=1

chrome --incognito --user-data-dir="/tmp" ;

ENABLE_WASM=0

doas sysctl kern.video.record=0
doas sysctl kern.audio.record=0
