#!/bin/sh

doas sysctl kern.video.record=1
doas sysctl kern.audio.record=1

doas chown alexander /dev/video0

ENABLE_WASM=1

chrome --incognito

ENABLE_WASM=0

doas sysctl kern.video.record=0
doas sysctl kern.audio.record=0

doas chown root /dev/video0
