#!/bin/sh

make_wallpaper() {
	_wallpaperdir="$HOME"/Pictures/Wallpapers/
	xwallpaper \
		--output eDP-1 --maximize "$(find "${_wallpaperdir}" -type f | sort -R | head -1)" \
		--output DP-1 --maximize "$(find "${_wallpaperdir}" -type f | sort -R | head -1)"
}

make_xbmpaper() {
	_black="#000000"
	_grey="#656565"
	_red="#b81313"
	_xbmdir="$HOME"/Pictures/XBMpapers/current/
	while true ; do
		xsetroot -bitmap "$(find "${_xbmdir}" -iname '*.xbm' | sort -R | head -1)" \
			-bg "${_grey}" \
			-fg "${_black}"
		sleep 3600
	done
}

if command -v xwallpaper > /dev/null ; then
	make_wallpaper
else
	make_xbmpaper
fi
