#!/bin/ksh

BLACK="#000000"
BLUE="#3b48e3"
GREEN="#18b218"
GREY="#656565"
RED="#b81313"
YELLOW="#b4801e"

while true ; do
	xsetroot -bitmap /home/alexander/Pictures/wallpaper-xbm/bw-bgnd/$(ls /home/alexander/Pictures/wallpaper-xbm/bw-bgnd/ | sort -R | tail -1) -bg "$GREY" -fg "$BLACK"
	sleep 3600
done
