#! /bin/sh

#https://www.zdf.de/comedy/heute-show/heute-show-vom-4-februar-2022-100.html

if [ -n "$2" ] ; then
	 _stream_id=$(youtube-dl -F "$2" | awk -F " " '/^hls/ { print $1 }' | tail -1)
else
	usage
fi

download_stream() {
	youtube-dl -f "${_stream_id}" "$2"
}

watch_with_mpv() {
	mpv --ytdl-raw-options="${_stream_id}" "$2"
}

usage() { cat << USAGE
${0##*/} - watch videos from the ZDF Mediathek.
usage: ${0##*/}	download -> Download the best quality stream.
		watch	 -> Watch the best quality stream with mpv(1).
USAGE
	exit 1
}

case $1 in
	d*) download_stream "$@" ;;
	w*) watch_with_mpv "$@" ;;
	*) usage ;;
esac
